// I in no way claim ownership or authorship of the following Thich Nhat Hanh quotes.
// Quotes were scraped from: http://www.goodreads.com/author/quotes/9074.Th_ch_Nh_t_H_nh
// There may still be some spelling mistakes and/or typos...
var quotes = [
"When another person makes you suffer, it is because he suffers deeply within himself, and his suffering is spilling over. He does not need punishment; he needs help. That's the message he is sending.",
"Sometimes your joy is the source of your smile, but sometimes your smile can be the source of your joy.",
"To be beautiful means to be yourself. You don’t need to be accepted by others. You need to accept yourself.",
"People usually consider walking on water or in thin air a miracle. But I think the real miracle is not to walk either on water or in thin air, but to walk on earth. Every day we are engaged in a miracle which we don't even recognize: a blue sky, white clouds, green leaves, the black, curious eyes of a child -- our own two eyes. All is a miracle.",
"People have a hard time letting go of their suffering. Out of a fear of the unknown, they prefer suffering that is familiar.",
"Smile, breathe and go slowly.",
"Because you are alive, everything is possible.",
"Waking up this morning, I smile. Twenty-four brand new hours are before me. I vow to live fully in each moment and to look at all beings with eyes of compassion.",
"The seed of suffering in you may be strong, but don't wait until you have no more suffering before allowing yourself to be happy.",
"Through my love for you, I want to express my love for the whole cosmos, the whole of humanity, and all beings. By living with you, I want to learn to love everyone and all species. If I succeed in loving you, I will be able to love everyone and all species on Earth... This is the real message of love.",
"My actions are my only true belongings.",
"Breathing in, I calm body and mind. Breathing out, I smile. Dwelling in the present moment I know this is the only moment.",
"Life is available only in the present moment.",
"Hope is important because it can make the present moment less difficult to bear. If we believe that tomorrow will be better, we can bear a hardship today.",
"Feelings come and go like clouds in a windy sky. Conscious breathing is my anchor.",
"We are here to awaken from our illusion of separateness.",
"Drink your tea slowly and reverently, as if it is the axis on which the world earth revolves - slowly, evenly, without rushing toward the future.",
"Many people think excitement is happiness....  But when you are excited you are not peaceful.  True happiness is based on peace.",
"Our own life has to be our message.",
"When we are mindful, deeply in touch with the present moment, our understanding of what is going on deepens, and we begin to be filled with acceptance, joy, peace and love.",
"Suffering is not enough. Life is both dreadful and wonderful...How can I smile when I am filled with so much sorrow? It is natural--you need to smile to your sorrow because you are more than your sorrow.",
"For things to reveal themselves to us, we need to be ready to abandon our views about them.",
"The source of love is deep in us and we can help others realize a lot of happiness. One word, one action, one thought can reduce another person’s suffering and bring that person joy.",
"By eating meat we share the responsibility of climate change, the destruction of our forests, and the poisoning of our air and water. The simple act of becoming a vegetarian will make a difference in the health of our planet.",
"When you say something really unkind, when you do something in retaliation your anger increases. You make the other person suffer, and he will try hard to say or to do something back to get relief from his suffering. That is how conflict escalates.",
"I promise myself that I will enjoy every minute of the day that is given me to live.",
"If you suffer and make your loved ones suffer, there is nothing that can justify your desire.",
"Keeping your body healthy is an expression of gratitude to the whole cosmos — the trees, the clouds, everything.",
"The past is gone, the future is not yet here, and if we do not go back to ourselves in the present moment, we cannot be in touch with life.",
"I have noticed that people are dealing too much with the negative, with what is wrong. ... Why not try the other way, to look into the patient and see positive things, to just touch those things and make them bloom?",
"Feelings, whether of compassion or irritation, should be welcomed, recognized, and treated on an absolutely equal basis; because both are ourselves. The tangerine I am eating is me. The mustard greens I am planting are me. I plant with all my heart and mind. I clean this teapot with the kind of attention I would have were I giving the baby Buddha or Jesus a bath. Nothing should be treated more carefully than anything else. In mindfulness, compassion, irritation, mustard green plant, and teapot are all sacred.",
"Walk as if you are kissing the Earth with your feet.",
"The wave does not need to die to become water. She is already water.",
"Root out the violence in your life, and learn to live compassionately and mindfully. Seek peace. When you have peace within, real peace with others is possible.",
"Compassion is a verb.",
"Understanding means throwing away your knowledge.",
"It is said that God has created man in his own image. But it may be that humankind has created God in the image of humankind.",
"The true miracle is not walking on water or walking in air, but simply walking on this earth.",
"The mind can go in a thousand directions, but on this beautiful path, I walk in peace. With each step, the wind blows. With each step, a flower blooms.",
"We have more possibilities available in each moment than we realize.",
"In true love, you attain freedom.",
"We often think of peace as the absence of war, that if powerful countries would reduce their weapon arsenals, we could have peace. But if we look deeply into the weapons, we see our own minds- our own prejudices, fears and ignorance. Even if we transport all the bombs to the moon, the roots of war and the roots of bombs are still there, in our hearts and minds, and sooner or later we will make new bombs. To work for peace is to uproot war from ourselves and from the hearts of men and women. To prepare for war, to give millions of men and women the opportunity to practice killing day and night in their hearts, is to plant millions of seeds of violence, anger, frustration, and fear that will be passed on for generations to come.",
"The secret of Buddhism is to remove all ideas, all concepts, in order for the truth to have a chance to penetrate, to reveal itself.",
"Thanks to impermanence, everything is possible.",
"The present moment is filled with joy and happiness.  If you are attentive, you will see it.",
"Each moment is a chance for us to make peace with the world, to make peace possible for the world, to make happiness possible for the world.",
"My actions are my only true belongings. I cannot escape the consequences of my actions. My actions are the ground on which I stand.",
"It is my conviction that there is no way to peace - peace is the way.",
"Until there is peace between religions, there can be no peace in the world.",
"To live in the present moment is a miracle. The miracle is not to walk on water. The miracle is to walk on the green Earth in the present moment, to appreciate the peace and beauty that are available now.",
"If our love is only a will to possess, it is not love.",
"Breathing in, there is only the present moment.",
"If you love someone, the greatest gift you can give them is your presence.",
"I am determined to practice deep listening. I am determined to practice loving speech.",
"If you love someone but rarely make yourself available to him or her, that is not true love.",
"Attachment to views is the greatest impediment to the spiritual path.",
"If we are peaceful, if we are happy, we can smile and blossom like a flower, and everyone in our family, our entire society, will benefit from our peace.",
"Letting go gives us freedom, and freedom is the only condition for happiness.  If, in our heart, we still cling to anything - anger, anxiety, or possessions - we cannot be free.",
"Peace is present right here and now, in ourselves and in everything we do and see. Every breath we take, every step we take, can be filled with peace, joy, and serenity. The question is whether or not we are in touch with it. We need only to be awake, alive in the present moment.",
"When we walk like (we are rushing), we print anxiety and sorrow on the earth. We have to walk in a way that we only print peace and serenity on the earth... Be aware of the contact between your feet and the earth. Walk as if you are kissing the earth with your feet.",
"To think in terms of either pessimism or optimism oversimplifies the truth. The problem is to see reality as it is.",
"If in our daily life we can smile, if we can be peaceful and happy, not only we, but everyone will profit from it. This is the most basic kind of peace work.",
"The kingdom of God is available to you in the here and the now. But the question is whether you are available to the kingdom. Our practice is to make ourselves ready for the kingdom so that it can manifest in the here and the now. You don't need to die in order to enter the kingdom of heaven. In fact, you have to be truly alive in order to do so.",
"If we are not fully ourselves, truly in the present moment, we miss everything.",
"Do not avoid contact with suffering or close your eyes before suffering. Do not lose awareness of the existence of suffering in the life of the world. Find ways to be with those who are suffering by all means, including personal contact and visits, images, sounds. By such means, ...awaken yourself and others to the reality of suffering in the world.  If we get in touch with the suffering of the world, and are moved by that suffering, we may come forward to help the people who are suffering.",
"In modern society most of us don't want to be in touch with ourselves; we want to be in touch with other things like religion, sports, politics, a book - we want to forget ourselves. Anytime we have leisure, we want to invite something else to enter us, opening ourselves to the television and telling the television to come and colonize us.",
"To dwell in the here and now does not mean you never think about the past or responsibly plan for the future.  The idea is simply not to allow yourself to get lost in regrets about the past or worries about the future.  If you are firmly grounded in the present moment, the past can be an object of inquiry, the object of your mindfulness and concentration. You can attain many insights by looking into the past.  But you are still grounded in the present moment.",
"From time to time, to remind ourselves to relax and be peaceful, we may wish to set aside some time for a retreat, a day of mindfulness, when we can walk slowly, smile, drink tea with a friend, enjoy being together as if we are the happiest people on Earth.",
"Because of your smile, you make life more beautiful.",
"You must love in such a way that the person you love feels free.",
"You are not an observer, you are a participant.",
"I would not look upon anger as something foreign to me that I have to fight... I have to deal with my anger with care, with love, with tenderness, with nonviolence.",
"The fact is that when you make the other suffer, he will try to find relief by making you suffer more. The result is an escalation of suffering on both sides.",
"The most precious gift we can offer anyone is our attention. When mindfulness embraces those we love, they will bloom like flowers.",
"At any moment, you have a choice, that either leads you closer to your spirit or further away from it.",
"Those who are without compassion cannot see what is seen with the eyes of compassion.",
"I am inviting you to go deeper, to learn and to practice so that you become someone who has a great capacity for being solid, calm, and without fear, because our society needs people like you who have these qualities, and your children, our children, need people like you, in order to go on, in order to become solid, and calm, and without fear.",
"In mindfulness one is not only restful and happy, but alert and awake. Meditation is not evasion; it is a serene encounter with reality.",
"Being rich is an obstacle to loving. When you are rich, you want to continue to be rich, and so you end up devoting all your time, all your energy, in your daily life to stay rich.",
"There is no enlightenment outside of daily life.",
"If you look deeply into the palm of your hand, you will see your parents and all generations of your ancestors. All of them are alive in this moment. Each is present in your body. You are the continuation of each of these people.",
"There is a story I would like to tell you about a woman who practices the invocation of the Buddha Amitabha's name. She is very tough, and she practices the invocation three times daily, using a wooden drum and a bell, reciting, 'Namo Amitabha Buddha' for one hour each time. When she arrives at one thousand times, she invites the bell to sound. (In Vietnamese, we don't say 'strike' or 'hit' a bell.) Although she has been doing this for ten years, her personality has not changed. She is still quite mean, shouting at people all the time.",
"Usually when we hear or read something new, we just compare it to our own ideas. If it is the same, we accept it and say that it is correct. If it is not, we say it is incorrect. In either case, we learn nothing.",
"In true dialog, both sides are willing to change.",
"If your love is only a will to possess, its not love.",
"A human being is like a television set with millions of channels.... We cannot let just one channel dominate us. We have the seed of everything in us, and we have to recover our own sovereignty.",
"Do not say that I'll depart tomorrow because even today I still arrive.",
"An oak tree is an oak tree. That is all it has to do. If an oak tree is less than an oak tree, then we are all in trouble.",
"The miracle is not to walk on water. The miracle is to walk on the green earth, dwelling deeply in the present moment and feeling truly alive.",
"Life can be found only in the present moment. The past is gone, the future is not yet here, and if we do not go back to ourselves in the present moment, we cannot be in touch with life.",
"Smile, breathe and go slowly.",
"May our heart's garden of awakening bloom with hundreds of flowers.",
"Earth will be safe when we feel in us enough safety.",
"Anyone can practice some nonviolence, even soldiers. Some army generals, for example, conduct their operations in ways that avoid killing innocent people; this is a kind of nonviolence. To help soldiers move in the nonviolent direction, we have to be in touch with them. If we divide reality into two camps - the violent and the nonviolent - and stand in one camp while attacking the other, the world will never have peace. We will always blame and condemn those we feel are responsible for wars and social injustice, without recognizing the degree of violence in ourselves. We must work on ourselves and also with those we condemn if we want to have a real impact.",
"You have to learn how to help  a wounded  child while still practicing mindful breathing. You should not allow yourself to get lost in action. Action should be meditation at the same time.",
"The problem is whether we are determined to go in the direction of compassion or not. If we are, then can we reduce the suffering to a minimum? If I lose my direction, I have to look for the North Star, and I go to the north. That does not mean I expect to arrive at the North Star. I just want to go in that direction.",
"It is possible to live twenty-four hours a day in a state of love. Every movement, every glance, every thought, and every word can be infused with love.",
"Please don't wait until the doctors tell you that you are going to have a baby to begin to take care of it. It is already there. Whatever you are, whatever you do, your baby will get it. Anything you eat, any worries that are on your mind will be for him or her. Can you tell me that you cannot smile? Think of the baby, and smile for him, for her, for the future generations. Please don't tell me that a smile and your sorrow just don't go together. It's your sorrow, but what about your baby? It's not his sorrow, its not her sorrow.",
"We who have touched war have a duty to bring the truth about war to those who have not had a direct experience of it. We are the light at the tip of the candle. It is really hot, but it has the power of shining and illuminating. If we practice mindfulness, we will know how to look deeply into the nature of war and, with our insight, wake people up so that together we can avoid repeating the same horrors again and again.",
"As long as you find something beautiful, good, and true to believe in and abide by, you have the equivalent of God in your life.",
"Happiness does not come from consumption of things.",
"I clean this teapot with the kind of attention I would have were I giving the baby Buddha or Jesus a bath.",
"Nonviolent action, born of the awareness of suffering and nurtured by love, is the most effective way to confront adversity.",
"Only the present moment contains life.",
"Our notions about happiness entrap us. We forget that they are just ideas. Our idea of happiness can prevent us from actually being happy. We fail to see the opportunity for joy that is right in front of us when we are caught in a belief that happiness should take a particular form.",
"Guarding knowledge is not a good way to understand. Understanding means to throw away your knowledge.",
"When you begin to see that your enemy is suffering, that is the beginning of insight.",
"The electron is first of all your concept of the electron.",
"Know that life can only be found in the present moment.",
"If we do not know how to take care of ourselves and to love ourselves, we cannot take care of the people we love. Loving oneself is the foundation for loving another person.",
"A real love letter is made of insight, understanding, and compassion. Otherwise it's not a love letter. A true love letter can produce a transformation in the other person, and therefore in the world. But before it produces a transformation in the other person, it has to produce a transformation within us. Some letters may take the whole of our lifetime to write.",
"Anyone can practice some nonviolence, even soldiers. Some army generals, for example, conduct their operations in ways that avoid killing innocent people; this is a kind of nonviolence.",
"During the last 2,500 years in Buddhist monasteries, a system of seven practices of reconciliation has evolved. Although these techniques were formulated to settle disputes within the circle of monks, i think they might also be of use in our households and in our society.",
"If you touch one thing with deep awareness, you touch everything.",
"I always encourage them to practice in a way that will help them go back to their own tradition and get re-rooted.  If they succeed at at becoming reintegrated, they will be an important instrument in transforming and renewing their tradition.",
"The raft is used to cross the river. It isn't to be carried around on your shoulders. The finger which points at the moon isn't the moon itself.",
"Breath is the bridge which connects life to consciousness, which unites your body to your thoughts. Whenever your mind becomes scattered, use your breath as the means to take hold of your mind again.",
"Sometimes it is better not to talk about art by using the word 'art'. If we just act with awareness and integrity, our art will flower, and we don't have to talk about it at all.",
"Before practicing meditation, we see that mountains are mountains.",
"The earth is so beautiful. We are beautiful also. We can allow ourselves to walk mindfully, touching the earth, our wonderful mother, with each step. We don't need to wish our friends, 'Peace be with you.' Peace is already with them. We only need to help them cultivate the habit of touching peace in each moment.",
"Each thought, each action in the sunlight of awareness becomes sacred.",
"Each time you look at a tangerine, you can see deeply into it. You can see everything in the universe in one tangerine. When you peel it and smell it, it’s wonderful. You can take your time eating a tangerine and be very happy.",
"Words and thoughts concerning compassionate action that are not put into practice are like beautiful flowers that are colorful but have no fragrance.",
"we are here to awaken from our illusion of separateness.",
"You would not cry if you knew that by looking deeply into the rain you would still see the cloud.",
"Your true home is in the here and the now.",
"Your breathing should flow gracefully.",
"I will practice coming back to the present moment...not letting regrets and sorrow drag me back into the past or letting anxieties, fears, or cravings pull me out...",
"Being vegetarian here also means that we do not consume dairy and egg products, because they are products of the meat industry. If we stop consuming, they will stop producing. Only collective awakening can create enough determination for action.",
"Peace can exist only in the present moment. It is ridiculous to say 'Wait until I finish this, then I will be free to live in peace.' What is 'this'? A diploma, a job, a house, the payment of a debt? If yo u th ink that way, peace will never come. There is always another 'this' that will follow the present one. If you are not living in peace at this moment, you will never be able to. If you truly want to be at peace, you must be at peace right now. Otherwise, there is only the hope of peace some day.",
"We have negative mental habits that come up over and over again. One of the most significant negative habits we should be aware of is that of constantly allowing our mind to run off into the future. Perhaps we got this from our parents. Carried away by our worries, we're unable to live fully and happily in the present. Deep down, we believe we can't really be happy just yet—that we still have a few more boxes to be checked off before we can really enjoy life. We speculate, dream, strategize, and plan for these 'conditions of happiness' we want to have in the future; and we continually chase after that future, even while we sleep. We may have fears about the future because we don't know how it's going to turn out, and these worries and anxieties keep us from enjoying being here now.",
"If you know how to be happy with the wonders of life that are already there for you to enjoy, you don't need to stress your mind and your body by striving harder and harder, and you don't need to stress this planet by purchasing more and more stuff. The Earth belongs to our children. We have already borrowed too much from it, from them; and the way things have been going, we're not sure we'll be able to give it back to them in decent shape. And who are our children, actually? They are us, because they are our own continuation. So we've been shortchanging our own selves. Much of our modern way of life is permeated by mindless overborrowing. The more we borrow, the more we loser. That's why it's critical that we wake up and see we don't need to do that anymore. What's already available in the here and now is plenty for us to be nourished, to be happy. Only that kind of insight will get us, each one of us, to stop engaging in the compulsive, self-sabotaging behaviors of our species. We need a collective awakening. One Buddha is not enough. All of us have to become Buddhas in order for our planet to have a chance. Fortunately, we have the power to wake up, to touch enlightenment from moment to moment, in our very own ordinary and, yes, busy lives. So let's start right now. Peace is your every breath.",
"Awareness is like the sun. When it shines on things, they are transformed.",
"If you do not know how to take care of yourself, and the violence in you, then you will not be able to take care of others. You must have love and patience before you can truly listen to your partner or child. If you are irritated you cannot listen. You have to know how to breath mindfully, embrace your irritation and transform it. Offer ONLY understand and compassion to your partner or child - This is the true practice of love.",
"If a child smiles, if an adult smiles, that is very important. If in our daily lives we can smile, if we can be peaceful and happy, not only we, but everyone will profit from it. If we really know how to live, what better way to start the day than with a smile? Our smile affirms our awareness and determination to live in peace and joy. The source of a true smile is an awakened mind.",
"When you look deeply into your anger, you will see that the person you call your enemy is also suffering. As soon as you see that, the capacity of accepting and having compassion for them is there."
];